POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "userID": "Shirley",
    "password": "qwerty"
    
}
###

POST http://localhost:8080/auth/loginBasic
Authorization: Basic ewogICAgInVzZXJJRCI6ICJTaGlybGV5IiwKICAgICJwYXNzd29yZCI6ICJxd2VydHkiCiAgICAKfQ==