###

POST http://localhost:8080/authenticate/loginBasic
Authorization: Basic ewogICAgInVzZXJuYW1lIjogIlNoaXJsZXkiLAogICAgInBhc3N3b3JkIjogInF3ZXJ0eSIKIH0=

###
POST http://localhost:8080/authenticate/register
Content-Type: application/json

{
    "username": "Shirley",
    "password": "qwerty",
    "email": "haha@haha.com"
}
###

PATCH http://localhost:8080/authenticate/resetPassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImlhdCI6MTYyMDA1MTU4MCwiZXhwIjoxNjIxNjc0NjMyMjAyfQ.HXQqaaCE7PNQyILu5VqL6zJuS9YeLtdArG7gHKn5Zos
Content-Type: application/json

{
    "newPw": "ewoibmV3UHciOiJxd2VyMTIzMTIzdHp1aW9wIgp9"   
}
###