POST https://localhost:8080/message/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMjEyNTIwMTc0MSwiaWF0IjoxNjIyMTE5MjAxfQ.v3mTtode1hQhw2YeYj96oBLPQ2wLTnSCWgIWboxIXI0
Content-Type: application/json

{
    "to": [
      "60af76903d30511694031f48",
      "60a406b2a7e9ce3dd856727c"      
    ],
    "content": "Hey, wie gehts?"
}

### get messages of logged in user
GET https://localhost:8080/message
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMjEyNTIwMTc0MSwiaWF0IjoxNjIyMTE5MjAxfQ.v3mTtode1hQhw2YeYj96oBLPQ2wLTnSCWgIWboxIXI0

