### post a new post
POST http://localhost:8080/post/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMTUyODA4MzQzNSwiaWF0IjoxNjIxNTI3NDgzfQ.MmP37HNTGQ6YabXkHIazIaeoi3cPu5ws7AI3-pphPPI
Content-Type: application/json

{
    "title": "Hanzo Main Guide",
    "postedBy": "60951807077e3357f084488d",
    "category": "Discuss",
    "tags": [{
        "map": "hanamura",
        "hero": "hanzo"
     }],
    "content": "Awesome content here..."
}
### get all posts
GET http://localhost:8080/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMTUzODczMzIwNSwiaWF0IjoxNjIxNTM4MTMzfQ.brisbimDm4O_Ukc3ZzBYG8VcWTQhHNysYSADdfhAmv8

### get post by id
GET http://localhost:8080/post/id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMTUyODA4MzQzNSwiaWF0IjoxNjIxNTI3NDgzfQ.MmP37HNTGQ6YabXkHIazIaeoi3cPu5ws7AI3-pphPPI
Content-Type: application/json

{
    "id": "60a662240bce15453057a094"
}

### get all posts of a user
GET http://localhost:8080/post/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMTUyODA4MzQzNSwiaWF0IjoxNjIxNTI3NDgzfQ.MmP37HNTGQ6YabXkHIazIaeoi3cPu5ws7AI3-pphPPI
Content-Type: application/json

{
    "id": "60951807077e3357f084488d"
}

### delete a post
DELETE http://localhost:8080/post/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMTUyODA4MzQzNSwiaWF0IjoxNjIxNTI3NDgzfQ.MmP37HNTGQ6YabXkHIazIaeoi3cPu5ws7AI3-pphPPI
Content-Type: application/json

{
    "id": "60a6353134e2df2c38d6ebba"
}

### update a post
PATCH http://localhost:8080/post/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMTUyODA4MzQzNSwiaWF0IjoxNjIxNTI3NDgzfQ.MmP37HNTGQ6YabXkHIazIaeoi3cPu5ws7AI3-pphPPI
Content-Type: application/json

{
    "id": "60a63ad30f63d443f84eaa4f",
    "title": "Genji Main Guide",
    "tags": [{"map": "route66", "hero": "hanzo"}],
    "content": "Awesome content here..."
}

### add a like to post 
PATCH http://localhost:8080/post/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMTUyODA4MzQzNSwiaWF0IjoxNjIxNTI3NDgzfQ.MmP37HNTGQ6YabXkHIazIaeoi3cPu5ws7AI3-pphPPI
Content-Type: application/json

{
    "idUser": "60951807077e3357f084488d",
    "idPost": "60a662240bce15453057a094"
}

### get all posts a user likes
GET http://localhost:8080/post/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMTUyODA4MzQzNSwiaWF0IjoxNjIxNTI3NDgzfQ.MmP37HNTGQ6YabXkHIazIaeoi3cPu5ws7AI3-pphPPI
Content-Type: application/json

{
    "id": "60951807077e3357f084488d"
}

### get latest posts for home view
GET http://localhost:8080/post/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMTUyODA4MzQzNSwiaWF0IjoxNjIxNTI3NDgzfQ.MmP37HNTGQ6YabXkHIazIaeoi3cPu5ws7AI3-pphPPI