GET https://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMjA2MDI1ODQ3NCwiaWF0IjoxNjIyMDU0MjU4fQ.UKpl8jZlYR7_dHpbIimU3f6x6pr96syMFn5Ardt4aiA

###

DELETE http://localhost:8080/users/user?id=60951807077e3357f084488d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMTU4OTkwOTkxNywiaWF0IjoxNjIxNTg5MzA5fQ.cANB6Dz7fzEA6PG5jCALtYVM-QJefdArATgZ4HlbWKg

### get one user

GET http://localhost:8080/users/id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMTU4OTkwOTkxNywiaWF0IjoxNjIxNTg5MzA5fQ.cANB6Dz7fzEA6PG5jCALtYVM-QJefdArATgZ4HlbWKg
Content-Type: application/json

{
    "id": "60a3a36d5f2b5344e4b66a07"   
}

### 

PATCH http://localhost:8080/users/id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMTU4OTkwOTkxNywiaWF0IjoxNjIxNTg5MzA5fQ.cANB6Dz7fzEA6PG5jCALtYVM-QJefdArATgZ4HlbWKg
Content-Type: application/json

{
    "id": "60a3a36d5f2b5344e4b66a07",
    "username": "Shirley",
    "email": "haha@haha.com"   
}