http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMTUyNjU3ODk3NCwiaWF0IjoxNjIxNTI1OTc4fQ.u7ZxJOg707CWsbeBfQiljDP_09J9NBAOEWBziZBlU5U
###

DELETE http://localhost:8080/users/user?id=6093f631bfff5f5560718362
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMDMxMzU1MzIwMCwiaWF0IjoxNjIwMzEyOTUzfQ.e8S1dxuKW9-p5B3_Blym45xNT3s95x5Ljg0e127jNJQ

###
