### create a new comment
POST https://localhost:8080/comment/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMjEyMjYzNTQ2NywiaWF0IjoxNjIyMTE2NjM1fQ.ADVhMVE77a-oDb6SAEPasAlzvYkCpiEoVn7DshzzJV8
Content-Type: application/json

{
    "post": "60a662240bce15453057a094",
    "content": "my first comment"
}

### get all comments to a post
GET https://localhost:8080/comment/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMjEyMjYzNTQ2NywiaWF0IjoxNjIyMTE2NjM1fQ.ADVhMVE77a-oDb6SAEPasAlzvYkCpiEoVn7DshzzJV8
Content-Type: application/json

{
    "post": "60a662240bce15453057a09"
}

### update a comment
PATCH https://localhost:8080/comment/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMjEyMjYzNTQ2NywiaWF0IjoxNjIyMTE2NjM1fQ.ADVhMVE77a-oDb6SAEPasAlzvYkCpiEoVn7DshzzJV8
Content-Type: application/json

{
    "id": "60af8ca199ab6750188c3909",
    "content": "New content here"
}

### delete a comment
DELETE  https://localhost:8080/comment/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyMjEyMjYzNTQ2NywiaWF0IjoxNjIyMTE2NjM1fQ.ADVhMVE77a-oDb6SAEPasAlzvYkCpiEoVn7DshzzJV8
Content-Type: application/json

{
    "id": "60af8bf4bbc03d3d445a5617"
}



