POST https://localhost:8080/message/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyNTc3NDAyNTk3MSwiaWF0IjoxNjI1NzY4MDI1fQ.V9St_saCM5l4R-TCoDFncmdkzVakJguyQFqYnC4L9OU
Content-Type: application/json

{
    "to": "60afc7cd43bd1c48d43711d2",
    "content": "Hey, wie gehts????"
}

###ADMIN

POST https://localhost:8080/message/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyNTgyNjc2OTI5NywiaWF0IjoxNjI1ODIwNzY5fQ.RMKYFkOVVzxdQ2EciFrerBj9wygSL7Io_0OeSw_UqOA
Content-Type: application/json

{
    "to": "60afb6f26de1ec1758dba853",
    "content": "Auch gut. Lust ranked zu spielen?"
}

### get messages of logged in user
GET https://localhost:8080/message
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiU2hpcmxleSIsImV4cCI6MTYyNTc1ODQ2ODUxMSwiaWF0IjoxNjI1NzUyNDY4fQ.HPQoN2bIbiHit_yTFjmIOazXAM71DKjeum51VRTB2eo

